### ISSUE TITLE
Openstack environment variable OS_USERNAME set wrong as OS_USER_NAME on collector.py

### ISSUE THREAD

**Issue by basivireddy** [CiscoSystems/don#13]
Traceback (most recent call last):
  File "vm_details_collector.py", line 244, in <module>
    print  main()
  File "vm_details_collector.py", line 241, in main
    return vms_details()
  File "vm_details_collector.py", line 226, in vms_details
    a1 = execute_cmd(['nova', 'list'], sudo=False, shell=False, env=env).split('\n');
  File "vm_details_collector.py", line 168, in execute_cmd
    universal_newlines=True).replace('\t', '    ')
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['nova', 'list']' returned non-zero exit status 1

**Comment by Miaodric** [comment]
Solution for this issue?

**Comment by amsaha** [comment]
Please use https://github.com/openstack/python-don. This issue should have been resolved there.
